# Generated by Django 2.2.16 on 2021-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Админ')], default='user', max_length=16),
        ),
    ]
