# Generated by Django 2.2.16 on 2021-12-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211201_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_User',
        ),
    ]
